name: Ask Jeremy to review PR
on:
  pull_request:
    types: [opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Assign Review Teams
      uses: rowi1de/auto-assign-review-teams@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        persons: jthake-msft
        include-draft: true
